name: BattlePassPlugin
main: com.memory.BattlePassPlugin
version: 1.10
api-version: 1.19
commands:
  bp:
    description: Opens the Battle Pass menu
    usage: /bp
    permission: battlepass.use
    permission-message: You do not have permission to use this command.
